services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      