services:
  server:
    image: cpu-ai-inference-server:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    restart: unless-stopped
    platform: linux/amd64